/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UltrassomSetorAeroportoRouteImport } from './routes/ultrassom-setor-aeroporto'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PediatraEmGoianiaRouteImport } from './routes/pediatra-em-goiania'
import { Route as OrtopedistaEmGoianiaRouteImport } from './routes/ortopedista-em-goiania'
import { Route as GinecologistaEmGoianiaRouteImport } from './routes/ginecologista-em-goiania'
import { Route as ExamesLaboratoriaisEmGoianiaRouteImport } from './routes/exames-laboratoriais-em-goiania'
import { Route as CardiologistaEmGoianiaRouteImport } from './routes/cardiologista-em-goiania'
import { Route as IndexRouteImport } from './routes/index'

const UltrassomSetorAeroportoRoute = UltrassomSetorAeroportoRouteImport.update({
  id: '/ultrassom-setor-aeroporto',
  path: '/ultrassom-setor-aeroporto',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PediatraEmGoianiaRoute = PediatraEmGoianiaRouteImport.update({
  id: '/pediatra-em-goiania',
  path: '/pediatra-em-goiania',
  getParentRoute: () => rootRouteImport,
} as any)
const OrtopedistaEmGoianiaRoute = OrtopedistaEmGoianiaRouteImport.update({
  id: '/ortopedista-em-goiania',
  path: '/ortopedista-em-goiania',
  getParentRoute: () => rootRouteImport,
} as any)
const GinecologistaEmGoianiaRoute = GinecologistaEmGoianiaRouteImport.update({
  id: '/ginecologista-em-goiania',
  path: '/ginecologista-em-goiania',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesLaboratoriaisEmGoianiaRoute =
  ExamesLaboratoriaisEmGoianiaRouteImport.update({
    id: '/exames-laboratoriais-em-goiania',
    path: '/exames-laboratoriais-em-goiania',
    getParentRoute: () => rootRouteImport,
  } as any)
const CardiologistaEmGoianiaRoute = CardiologistaEmGoianiaRouteImport.update({
  id: '/cardiologista-em-goiania',
  path: '/cardiologista-em-goiania',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardiologista-em-goiania': typeof CardiologistaEmGoianiaRoute
  '/exames-laboratoriais-em-goiania': typeof ExamesLaboratoriaisEmGoianiaRoute
  '/ginecologista-em-goiania': typeof GinecologistaEmGoianiaRoute
  '/ortopedista-em-goiania': typeof OrtopedistaEmGoianiaRoute
  '/pediatra-em-goiania': typeof PediatraEmGoianiaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ultrassom-setor-aeroporto': typeof UltrassomSetorAeroportoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardiologista-em-goiania': typeof CardiologistaEmGoianiaRoute
  '/exames-laboratoriais-em-goiania': typeof ExamesLaboratoriaisEmGoianiaRoute
  '/ginecologista-em-goiania': typeof GinecologistaEmGoianiaRoute
  '/ortopedista-em-goiania': typeof OrtopedistaEmGoianiaRoute
  '/pediatra-em-goiania': typeof PediatraEmGoianiaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ultrassom-setor-aeroporto': typeof UltrassomSetorAeroportoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardiologista-em-goiania': typeof CardiologistaEmGoianiaRoute
  '/exames-laboratoriais-em-goiania': typeof ExamesLaboratoriaisEmGoianiaRoute
  '/ginecologista-em-goiania': typeof GinecologistaEmGoianiaRoute
  '/ortopedista-em-goiania': typeof OrtopedistaEmGoianiaRoute
  '/pediatra-em-goiania': typeof PediatraEmGoianiaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ultrassom-setor-aeroporto': typeof UltrassomSetorAeroportoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardiologista-em-goiania'
    | '/exames-laboratoriais-em-goiania'
    | '/ginecologista-em-goiania'
    | '/ortopedista-em-goiania'
    | '/pediatra-em-goiania'
    | '/sitemap.xml'
    | '/ultrassom-setor-aeroporto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardiologista-em-goiania'
    | '/exames-laboratoriais-em-goiania'
    | '/ginecologista-em-goiania'
    | '/ortopedista-em-goiania'
    | '/pediatra-em-goiania'
    | '/sitemap.xml'
    | '/ultrassom-setor-aeroporto'
  id:
    | '__root__'
    | '/'
    | '/cardiologista-em-goiania'
    | '/exames-laboratoriais-em-goiania'
    | '/ginecologista-em-goiania'
    | '/ortopedista-em-goiania'
    | '/pediatra-em-goiania'
    | '/sitemap.xml'
    | '/ultrassom-setor-aeroporto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardiologistaEmGoianiaRoute: typeof CardiologistaEmGoianiaRoute
  ExamesLaboratoriaisEmGoianiaRoute: typeof ExamesLaboratoriaisEmGoianiaRoute
  GinecologistaEmGoianiaRoute: typeof GinecologistaEmGoianiaRoute
  OrtopedistaEmGoianiaRoute: typeof OrtopedistaEmGoianiaRoute
  PediatraEmGoianiaRoute: typeof PediatraEmGoianiaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UltrassomSetorAeroportoRoute: typeof UltrassomSetorAeroportoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ultrassom-setor-aeroporto': {
      id: '/ultrassom-setor-aeroporto'
      path: '/ultrassom-setor-aeroporto'
      fullPath: '/ultrassom-setor-aeroporto'
      preLoaderRoute: typeof UltrassomSetorAeroportoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pediatra-em-goiania': {
      id: '/pediatra-em-goiania'
      path: '/pediatra-em-goiania'
      fullPath: '/pediatra-em-goiania'
      preLoaderRoute: typeof PediatraEmGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ortopedista-em-goiania': {
      id: '/ortopedista-em-goiania'
      path: '/ortopedista-em-goiania'
      fullPath: '/ortopedista-em-goiania'
      preLoaderRoute: typeof OrtopedistaEmGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ginecologista-em-goiania': {
      id: '/ginecologista-em-goiania'
      path: '/ginecologista-em-goiania'
      fullPath: '/ginecologista-em-goiania'
      preLoaderRoute: typeof GinecologistaEmGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames-laboratoriais-em-goiania': {
      id: '/exames-laboratoriais-em-goiania'
      path: '/exames-laboratoriais-em-goiania'
      fullPath: '/exames-laboratoriais-em-goiania'
      preLoaderRoute: typeof ExamesLaboratoriaisEmGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardiologista-em-goiania': {
      id: '/cardiologista-em-goiania'
      path: '/cardiologista-em-goiania'
      fullPath: '/cardiologista-em-goiania'
      preLoaderRoute: typeof CardiologistaEmGoianiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardiologistaEmGoianiaRoute: CardiologistaEmGoianiaRoute,
  ExamesLaboratoriaisEmGoianiaRoute: ExamesLaboratoriaisEmGoianiaRoute,
  GinecologistaEmGoianiaRoute: GinecologistaEmGoianiaRoute,
  OrtopedistaEmGoianiaRoute: OrtopedistaEmGoianiaRoute,
  PediatraEmGoianiaRoute: PediatraEmGoianiaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UltrassomSetorAeroportoRoute: UltrassomSetorAeroportoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
